#!/bin/bash
sudo rpm -Uvh https://yum.puppet.com/puppet5/puppet5-release-el-7.noarch.rpm >> ~/install.log
export PATH=/opt/puppetlabs/bin:$PATH >> ~/install.log
sudo yum install -y puppet-agent >> ~/install.log
sudo /opt/puppetlabs/bin/puppet resource service puppet ensure=running enable=true >> ~/install.log
puppet --version >> ~/install.log