#!/bin/bash
sudo wget https://apt.puppet.com/puppet5-release-xenial.deb >> ~/install.log
sudo dpkg -i puppet5-release-xenial.deb >> ~/install.log
sudo apt-get update >> ~/install.log
sudo apt-get install -y puppet-agent >> ~/install.log
export PATH=/opt/puppetlabs/bin:$PATH >> ~/install.log
sudo /opt/puppetlabs/bin/puppet resource service puppet ensure=running enable=true >> ~/install.log
puppet --version >> ~/install.log
sudo systemctl start puppet >> ~/install.log
sudo systemctl enable puppet >> ~/install.log
